services:
  postgres:
    image: postgres:15.3
    volumes:
      - './src/main/resources/product.sql:/docker-entrypoint-initdb.d/02-product.sql'
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
      POSTGRES_DB: product
    ports:
      - 5432:5432